package com.example.produtosapi.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "produto")
public class Produto {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String produtoId;

    @DynamoDBAttribute
    private String nome;

    @DynamoDBAttribute
    private String preco;

    public String getProdutoId() {
        return produtoId;
    }

    public void setProdutoId(String produtoId) {
        this.produtoId = produtoId;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getPreco() {
        return preco;
    }

    public void setPreco(String preco) {
        this.preco = preco;
    }

    public Produto(String produtoId, String nome, String preco) {
        this.produtoId = produtoId;
        this.nome = nome;
        this.preco = preco;
    }

    public Produto() {
    }

    //{
    //    "TableDescription": {
    //        "AttributeDefinitions": [
    //            {
    //                "AttributeName": "produtoId",
    //                "AttributeType": "S"
    //            }
    //        ],
    //        "TableName": "produto",
    //        "KeySchema": [
    //            {
    //                "AttributeName": "produtoId",
    //                "KeyType": "HASH"
    //            }
    //        ],
    //        "TableStatus": "ACTIVE",
    //        "CreationDateTime": "2024-01-13T21:48:31.808000-03:00",
    //        "ProvisionedThroughput": {
    //            "ReadCapacityUnits": 1,
    //            "WriteCapacityUnits": 1
    //        },
    //        "TableSizeBytes": 0,
    //        "ItemCount": 0,
    //        "TableArn": "arn:aws:dynamodb:us-east-1:000000000000:table/produto",
    //        "TableId": "515167c8-fd16-41d4-a63c-6ced412fc7a2",
    //        "DeletionProtectionEnabled": false
    //    }
    //}

}
